name = "CentralNetworkScheme"
uuid = "6957fbe9-b49b-4ae6-aed7-1e9f49c9bb60"
authors = ["Niklas Kolbe <nklb@mailbox.org>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
